name: test-mim

on:
  push:
    paths:
      - '.github/workflows/test_mim.yml'
      - 'pyproject.toml'
      - 'setup.py'
      - 'model-index.yml'
      - 'configs/**'
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/test_mim.yml'
      - 'pyproject.toml'
      - 'setup.py'
      - 'model-index.yml'
      - 'configs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_mim_cpu:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']
        torch: ['2.5.1']
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{matrix.python-version}}
          activate-environment: true
      - name: Install PyTorch
        run: |
          uv pip install --torch-backend=cpu torch==${{ matrix.torch }} torchvision
          uv pip install importlib-metadata
      - name: Install mim
        run: uv pip install "onedl-mim>=0.4.0rc2"
      - name: Build and install
        run: mim install .
      - name: test commands of mim
        env:
          PAGER: cat
          LESS: ""
          MORE: ""
          MANPAGER: cat
        run: mim search onedl-mmsegmentation
